### ISSUE TITLE
python interface

### ISSUE THREAD

**Issue by okdistribute** [pkafei/Dat-Python#2]
It makes sense to first implement a dat module that we can put on pypi. This is just an initial proposal and it is wide open for comment/change
# Creation

External source (REST api)

```
from dat import Dat
dat = Dat('http://my-dat.karissamck.com', version='version-number')
```
# Fetching data

Generators (using yield, streaming)

```
for row in dat.rows():
   print(row)
```

Pandas dataframe (will pose problems for very large datasets)

```
df = dat.to_pandas()
```

**Comment by pkafei** [comment]
This is a good feedback, thanks. So I'm assuming when the users `import dat` they are performs a dat init. At this point I would like to use functions before using generators. I am starting simple and creating GET calls before POST. Finally, I would like to talk to you and @finnp about good API design in general.

**Comment by okdistribute** [comment]
Great call today -- we talked about an initial structure and next steps, here's a suggested first step that will make packaging and putting it on pypi a little easier

**dat.py**

``` python
class Dat:
   def __init__(host):
      self.host = host

   def _call(path):
      api = self.host + path
      # authenticate/calls api?

   def rows():
       # calls _call, makes python object?

   def to_pandas():
       # calls pd.read_csv?
```

**test.py**

``` python
from dat import Dat
test_dat = Dat('http://my-test-dat.dathub.org')
```

**Comment by pkafei** [comment]
I'm also happy we got a chance to talk. Thanks for the boilerplate- I will take what I have in https://github.com/pkafei/Dat-Python/blob/master/streaming_dat.py and refactor it into class Dat.
